server:
  port: 8083

spring:
  devtools:
    restart:
      enabled: true  #热部署生效
      additional-paths: src/main/java  #设置重启的目录,添加那个目录的文件需要restart
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/repair_system?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      username: root
      password: 123456
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #解决列名必须下划线的问题
    properties:
      hibernate:
        hbm2ddl:
          auto: validate

# JWT
jwt:
  header: Authorization
  secret-key: jwtbanzhuan
  tokenHead: "Bearer "

#微信配置
wechat:
  app_id: wx3e8f2155d7875447
  secret: b01b2b6813602e79957dd16fb51f5f69
