server:
  port: 8082

hmac:
  secretKey: banzhuan
  algorithm: HmacMD5


#热部署生效
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java  #设置重启的目录,添加那个目录的文件需要restart
