server:
  port: 8443
  ssl:
    key-store: classpath:guohanghuang.cn.jks
    key-store-password: 3116004636
    keyStoreType: JKS

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    account-service:
        path: /account-service/**
        serviceId: ACCOUNT-SERVICE  #这里写eureka的中注册的服务id
        stripPrefix: false
        sensitiveHeaders:
    backend-service:
        path: /backend-service/**
        serviceId: BACKEND-SERVICE
        stripPrefix: false
        sensitiveHeaders:
    repair-service:
      path: /repair-service/**
      serviceId: REPAIR-SERVICE
      stripPrefix: false
      sensitiveHeaders:

jwt:
  secret-key: jwtbanzhuan
