server:
  port: 80

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    account-service:
        path: /account-service/**
        serviceId: ACCOUNT-SERVICE  #这里写eureka的中注册的服务id
        stripPrefix: false
        sensitiveHeaders:
    address-service:
        path: /address-service/**
        serviceId: ADDRESS-SERVICE
        stripPrefix: false
        sensitiveHeaders:
    backend-service:
        path: /backend-service/**
        serviceId: BACKEND-SERVICE
        stripPrefix: false
        sensitiveHeaders:
    repair-service:
      path: /repair-service/**
      serviceId: REPAIR-SERVICE
      stripPrefix: false
      sensitiveHeaders:

jwt:
  secret-key: jwtbanzhuan

